### ISSUE TITLE
Some questions about outer product

### ISSUE THREAD

**Issue by deltaguo** [UDC-GAC/openCNN#1]
I have a rough idea of your algorithmic process, but still have some doubts. The paper describes that each thread calculates two 8\*8\*8 GEMMs, and each iteration needs to calculate 16 batches of BK\*BC\*BN GEMMs. In your code, it is described as matrix multiplication of two 2*8 inputs and filters. I feel a little confused and don't know the relationship between these descriptions.

I test your code on the A100 and get normal results.
And then I tested your code on MI100, which architecture is CDNA, some differences I know are 64 threads per warp, the experimental results are calculated correctly, but very inefficient. I found that the process of transforming the result of matrix multiplication is the most time-consuming. But I haven't understood the previous code.
![image](https://user-images.githubusercontent.com/49133878/196115754-25c46ee2-06d8-4a42-b7c5-a71d4bc00d68.png)
I also hope to get some inspiration, whether it is the difference in architecture that causes such a big difference in efficiency.

**Comment by FSSRepo** [comment]
Which was the fix?
